### ISSUE TITLE
Latest build broken compatibility with Applied Energistics 2

### ISSUE THREAD

**Issue by Ragnarok96** [TheCBProject/NotEnoughItems#159]
The "JEI Synchronized Auto" option for the search bar on the ME Crafting Terminals does NOT work with the latest update on MC 1.12.2 however it did use to work. Is NEI no longer an addon mod to JEI? if NEI is toggled off so the JEI search and styles are used then the search box works as it should again.

**Comment by covers1624** [comment]
At the moment, the option to switch between NEI and JEI styles doesnt actually 'change' JEI's style, it displays NEI's separate item panel and search box, in the future this will change, but at the moment its a large amount of work, and something mezz and i need to discuss more. Thats why it doesnt work, because AE2 only has integration for JEI not NEI, and thats how it should be, NEI's API is deprecated and will be removed at some point.
