### ISSUE TITLE
[Not A Bug] JEI Lacks, NEI now lacks as well

### ISSUE THREAD

**Issue by DrZed** [TheCBProject/NotEnoughItems#34]
I miss the old feature to drag items from NEI for "ghost" items, to use in filters for various item transport systems, extra utils was one of the only mods that used it, but it was hella useful for setting up automated systems without screwing things up waiting for stuff to get processed to get the items for filtering.

I personally hate JEI, and would like it if you can to fully update old NEI to 1.10.2, if you do you have my thanks, obviously you have no obligation to do anything anyone requests, but still, my request has been made.

**Comment by Bennyboy1695** [comment]
Not to but in on this topic, but i feel this is kinda relevant. But I see no point in having JEI as a core mod to NEI when they basically do the same thing. I know its done because the code wasnt able to be brought up to 1.10 but it just seems rather weird to have a mod that does the same thing as a core mod 😛

**Comment by covers1624** [comment]
There is a difference between coremod and dependency, i have JEI as a DEPENDENCY because people are supporting JEI's much nicer and cleaner API and if people only installed NEI thinking that it doesn't matter, users would go and complain to mod authors that "OMGG WHY U NO NEI RECIPEE, YOUR MOD SUX". No on to the actual issue at hand here, it would be ideal if JEI were to have this. @mezz feature request?? :P

**Comment by mezz** [comment]
Sure, make a request on the JEI github.
>I personally hate JEI,

Not winning any favors though.

**Comment by Bennyboy1695** [comment]
I meant dependency when I said core mod, was late when I wrote that :P But I still find it weird and kinda silly to have a mod like NEI depend on a mod that's almost exactly the same. I understand that it's calling on some things from jei but would it not make more sense to have NEI do those things itself and then people can choose between JEI and NEI instead.

**Comment by covers1624** [comment]
Thats not the point of having it as a dep. Mods WILL NOT have recipes if NEI is the only one installed BECAUSE people are supporting JEI's api. NEI has never handled recipes for every mod under the sun, the mod writes integration for NEI / JEI.

**Comment by Bennyboy1695** [comment]
I understand that people have supported jei's api but they could easily support nei too if it was separate. I am not hating on jei, I like jei I just find it kinda pointless to have the two mods that do the same need to be linked :P

**Comment by covers1624** [comment]
Its getting people to support 2 api's for 2 mods that do the same thing. Yes i could work like that but why.. To most people it sounds simple, but modders are lazy, if they don't have to write something they wont.

**Comment by Bennyboy1695** [comment]
You basically just said what I mean there, maybe not a lot of modders would do both api's. Buts it's the same with the users not a lot of users would install 2 mods that do the same just to use the other.

**Comment by DrZed** [comment]
I don't like JEI for one thing that stands out the most, Load time, I have a massive load time partially due to JEI's Recipe Itemstacks, I have 100~ mods and I have 1 minute 13 seconds extra load time when JEI is loading 300k Itemstacks. (my total load time is 3 minutes 15 seconds give or take a few seconds)

And as I mentioned before a few more features JEI lacks that I found originally helpful.

>  I agree @mezz Im sick of the slander against JEI,

Lol funny thing is I can say the same about Optifine, many thousands of people slander optifine and I love to defend it, since sp416x is a highly skilled programmer higher than most in this community

**Comment by mezz** [comment]
Report your issue to the JEI issue tracker and work with me to see if it can be fixed, instead of complaining to unrelated people.

Optifine gets dissed by modders because it doesn't follow standard practices for mod compatibility and it is closed source, so issues with it are painful to diagnose. Waste enough hours on a mystery issue with your mod that somehow turns out to be an Optifine problem and you'd be annoyed too. Other people hear the horror story and parrot that sentiment and there you go, negative reputation.

**Comment by DrZed** [comment]
A.) I cannot report it as your guidelines clearly state do not request NEI features
B.) I don't think my loadtime issue is on the "release" only on the beta on curse.
C.) I will be better off finding the issue with load time myself, and creating a pull request or at least telling you where the issue is from, as just saying "it's broken doing this" isn't a valid bug report for **me** to send in my book.

**Comment by DatrixTHLK** [comment]
@mezz @DrZed  Well then the least they could do is when reporting a rendering issue they take it straight to Optifine themselves to have them take a look at it. It is the least anyone can do. Instead of just saying "I hate optifine because I can't find a certain issue someone else said IS wrong with mod A yet doesn't appear as an issue on my mod A's end." Then just tell them "this is not my issue but optifines." I still like Optifine even though rendering issues happens. In this situation, I will just either get rid of the mod that is causing said issue or tell optifine about said issue. MHO. Anyways, I've rambled on for long enough.
