### ISSUE TITLE
[2.1.1.142] "Missing" required mods

### ISSUE THREAD

**Issue by iamomicron** [TheCBProject/NotEnoughItems#4]
Attempting to install the latest NEI (2.1.1.142) on MC 1.10.2 causes a 'missing mods' issue, where there are no required mods actually missing. (Although strangely, the Forge GUI does not actually appear for myself)

[Here's a GUI screenshot from another user with the problem however](http://i.imgur.com/LYjYLc0.png)

[And here's my crash log in case of a related issue](http://pastebin.com/PDwrkHFp)

* I've tried both these Forge versions:
    * 12.18.1.2011
    * 12.18.1.2049
* I've tried these versions of JEI:
    * jei_1.10.2-3.7.10.237.jar
    * jei_1.10.2-3.7.11.238.jar
* I have the latest versions of CodeChickenCore and CodeChickenLib.

Other uses also have this problem, highlighted on the original NEI MCF post: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279956-chickenbones-mods?comment=23815

**Comment by covers1624** [comment]
Yeah.. Im still working on 1.10 and have some improvements in CCL so
im waiting for those to be finished before i push any 1.10 releases,
regarding the required mods, it is entirely possible i goofed the
required JEI version. 

----- Original Message -----
From: "TheCBProject/NotEnoughItems" 
To:"TheCBProject/NotEnoughItems" 
Cc:
Sent:Tue, 09 Aug 2016 11:25:52 -0700
Subject:[TheCBProject/NotEnoughItems] [2.1.1.142] "Missing" required
mods (#4)

	Attempting to install the latest NEI (2.1.1.142) causes a 'missing
mods' issue, where there are no required mods actually missing.
(Although strangely, the Forge GUI does not actually appear for
myself) 

	Here's a GUI screenshot from another user with the problem however
[1] 

	And here's my crash log in case of a related issue [2] 

	* I've tried both these Forge versions: 

	* 12.18.1.2011
 	* 12.18.1.2049

	* I've tried these versions of JEI: 

	* jei_1.10.2-3.7.10.237.jar
 	* jei_1.10.2-3.7.11.238.jar

 	* I have the latest versions of CodeChickenCore and CodeChickenLib.

	Other uses also have this problem, highlighted on the original NEI
MCF post:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279956-chickenbones-mods?comment=23815
[3] 

	—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub [4], or mute the
thread [5].     

Links:
------
[1] http://i.imgur.com/LYjYLc0.png
[2] http://pastebin.com/PDwrkHFp
[3]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279956-chickenbones-mods?comment=23815
[4] https://github.com/TheCBProject/NotEnoughItems/issues/4
[5]

**Comment by djchena** [comment]
yes, same here, i try all combinations of mods and forge, with the same result all times

**Comment by covers1624** [comment]
Fixed hopefully in newest version.
