### ISSUE TITLE
Plan to Update?

### ISSUE THREAD

**Issue by Etrainquandt17** [TheCBProject/NotEnoughItems#70]
Do you plan to update this mod to be like the original version. I don't like that it requires JEI. I also really liked the feature of unlimited items. I miss the old NEI :(. If you plan to update it I will be so happy.

**Comment by gigabit101** [comment]
1. If it dose go back expect no mod support mod authors will not want to support both.
2. There is no problem with it being a JEI addon its works fine and has the benefit of JEI's API (So much nicer)

**Comment by covers1624** [comment]
So, here is the path that NEI is taking. It IS being moved to a JEI addon that simply skins JEI to look and fee like NEI, the issues with NEI going back to a standalone mod is, NEI doesnt actually provide the recipe handlers that show you all the custom stuff from mods, that is the mod doing it using NEI's api, that being said the same thing is happening with JEI mods are supporting it instead of NEI, You will be back to this tracker in 5 min complaining that there is no recipes, it just doesnt work that way sadly.

**Comment by Etrainquandt17** [comment]
Ok I Understand, at least it has some features like the potion GUI and the encant GUI.
