### ISSUE TITLE
Items hidden in JEI are visible in NEI (MC 1.10.2) - Bug (?)

### ISSUE THREAD

**Issue by Vaygrim** [TheCBProject/NotEnoughItems#90]
I'm using JEI 3.14.416 with NEI 2.1.3.207 in a modpack I'm developing and I've noticed something fairly problematic. Specifically, any items / recipes / blocks hidden from JEI using things like Minetweaker or UniDict (a mod used for ore / ingot unification and simplification) are visible if we use the NEI ItemPanel and Searchbox.

I actually prefer the NEI interface, and NEI ItemPanel / SearchBox .. but I can't find a way for NEI to 'honor' JEI's hidden objects.

HELP?

**Comment by covers1624** [comment]
Ah, this has been a missing chunk of integration ive been meaning to get to. Ill see what i can do for 1.10 but it will exist in 1.11.

**Comment by covers1624** [comment]
Can you please verify the feature is working as inteded with [this](http://chickenbones.net/maven/codechicken/NotEnoughItems/1.10.2-2.1.3.218/) version. If so ill push it to curse.

**Comment by Vaygrim** [comment]
Checked the linked version, still a problem. In JEI I will only see 1 Copper Ingot. Using all NEI (ItemPanel, Searchbox) I see 4 Copper Ingots.

**Comment by obuw** [comment]
I just wanted to say that I also stumbled onto this issue today, when I tried to add NEI to the Age of Engineering modpack. It's showing the default recipes for the blocks instead of the minetweaked ones.

Perhaps it is a loading sequence thing? Like it's being loaded before the minetweaker scripts take place?
